### ISSUE TITLE
Numéro vert

### ISSUE THREAD

**Issue by adriens** [adriens/covid19-action-plan-nc#16]
Ajouter le numéro vert

![image](https://user-images.githubusercontent.com/5235127/77315485-bf783880-6d5b-11ea-9675-1eb055dd80a1.png)

Idéalement, le rendre cliquable afin de mettre la source d'info au plus proche de l'utilisateur final.

**Comment by sschorgen** [comment]
C'est fait :)
Site officiel + numéro vert ajouté en haut à droite.

**Comment by adriens** [comment]
screnshot de démo ❔

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/77376578-bb343580-6dc4-11ea-915b-76f82530a5fa.png)
