### ISSUE TITLE
Cache planté sur certaines instances chez certaines personnes > BEST EFFORT POUR DISPO HEURE DE POINTE

### ISSUE THREAD

**Issue by adriens** [adriens/covid19-action-plan-nc#17]
![image](https://user-images.githubusercontent.com/5235127/77393840-03b61800-6df2-11ea-96ec-09aeb25ca086.png)

**Comment by adriens** [comment]
Sylver SCHORGEN 5:07 PM

default cache de chrome = 24h ...

chromium

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/77394050-87700480-6df2-11ea-9c54-a5830c9cf94f.png)

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/77394320-298fec80-6df3-11ea-9c9b-5be82c543d73.png)

**Comment by adriens** [comment]
![Uploading image.png…]()

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/77394489-a327da80-6df3-11ea-9b22-6c40e5c7ae78.png)

**Comment by sschorgen** [comment]
En effet je confirme pb de cache navigateur suite à un changement de l'URL du rapport public PBI.
URL forcée à partir de maintenant

**Comment by sschorgen** [comment]
on continue les investigations pour les autres cas

**Comment by sschorgen** [comment]
OK, c'est corrigé.
Durée de l'incident : 40 minutes
Cause de l'incident : Problème de cache navigateur
Résolution : Utilisation d'une redirection définitive côté OVH
Côté PBI : Utilisation d'une URL unique pour les nouveaux rapports [En cours de configuration]

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/77394554-c8b4e400-6df3-11ea-8382-ff3482becf00.png)

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/77396838-9a85d300-6df8-11ea-8388-fc12c2479151.png)

**Comment by adriens** [comment]
Top, merci à tous, l'incident est fixé pour le coup de feu du soir
