### ISSUE TITLE
Ajout d'un QrCode sur tbaleau de bord

### ISSUE THREAD

**Issue by adriens** [adriens/covid19-action-plan-nc#18]
# Objectif

Partager aisément le tdb. Je vois un tableau de bord sur un device chez quelqu'un et je le veux.

# Actions

- [x] Créer un QrCode customizé
- [ ] Sur le tableau de bord ajouter le QrCode qui vi aun lien bitly dédié (lisivilité QrCode et stats d'utilisation) renvoie vers l'url du tdb. Selon le device ce sera la version mobile ou pc

**Comment by adriens** [comment]
@sschorgen , vola


![qr-code-covid-19nc](https://user-images.githubusercontent.com/5235127/77471910-36e6be80-6e67-11ea-9701-c5e0b14032d8.png)

**Comment by adriens** [comment]
@sschorgen , tu vas le déployer ou finalement t pas chaud ? Si projetée sur un TV, le tdb sera facilement copiable par les personnes intéressées sur leur device.
C'est un ticke tà faire complexité

**Comment by sschorgen** [comment]
est-ce qu'on le partage pas sur les réseaux sociaux plutôt ? 
QRCode qui renvoie sur le même lien pas bizzare ? :)

**Comment by adriens** [comment]
"QRCode qui renvoie sur le même lien pas bizzare ? :)"

-> Non, le scénario est le suivant:


1. Je suis dans une salle d'attente
2. Je vois le contenu du dashboard diffusé sur une TV our sur l'écran de PV/tablette/tel de mon voisin
3. Je veux ce contenu moi aussi mais ne pas donner mon contact ni taper l'url (sur un tel c pénible)
4. Je flashe le QrCode
5. J'accède au Tdb sur mon device et en fais ce que je veux depuis ce device
6 - FIN

**Comment by sschorgen** [comment]
OK Done :)

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/77718591-65b38f00-7037-11ea-95f0-ea54c6605676.png)

**Comment by adriens** [comment]
Le Qr est super robuste, même tout petit ça catche nickel et très vite. 👏
