### ISSUE TITLE
Date et heure de prochain refresh du Tdb

### ISSUE THREAD

**Issue by adriens** [adriens/covid19-action-plan-nc#19]
# Constat

Je reçois de nombreuses demandes de personnes qui veulent savoir quand le tdb sera mis à jour

# Proposition

Afficher la date/heure du prochain refresh de cache afin de donner une pespective

**Comment by adriens** [comment]
(moi-même je me le demande, je fais F5 comme un dingue quand suis sur #7

**Comment by sschorgen** [comment]
![image](https://user-images.githubusercontent.com/11071408/77608271-cf1c9a80-6f70-11ea-9150-be742782c734.png)

C'est fait :)

**Comment by adriens** [comment]
stylé 👍
