### ISSUE TITLE
Courbe historisée Cas Importés vs cas locaux

### ISSUE THREAD

**Issue by adriens** [adriens/covid19-action-plan-nc#20]

**Comment by adriens** [comment]
Upvote par [Patrick Schmitt](https://www.linkedin.com/in/patrick-schmitt-5883b6109/)


![image](https://user-images.githubusercontent.com/5235127/77604154-ec983700-6f65-11ea-8895-f4502622247b.png)

**Comment by adriens** [comment]
Priorité passée en 1️⃣  sur la TODO List

**Comment by adriens** [comment]
Lancement des dévs ce soir cf @sschorgen 👍

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/77607831-a3e57b80-6f6f-11ea-919a-79121b7a10c0.png)

**Comment by adriens** [comment]
👍  @sschorgen  c bien en ligne 👏

**Comment by sschorgen** [comment]
Dév fait et poussé en prod :)
