### ISSUE TITLE
Titre (méta) de la page web du tdb > Remplacer "MS Power BI" par uatre chose

### ISSUE THREAD

**Issue by adriens** [adriens/covid19-action-plan-nc#21]
![image](https://user-images.githubusercontent.com/5235127/77411457-95348280-6e10-11ea-87e3-2dbee8b00b43.png)

**Comment by sschorgen** [comment]
Site redéveloppé avec la bonne méta :)
![image](https://user-images.githubusercontent.com/11071408/77608356-14d96300-6f71-11ea-9590-b140251cb4ac.png)

**Comment by adriens** [comment]
Je confirme ✔️
