### ISSUE TITLE
Implémenter le "Open Graph protocol"

### ISSUE THREAD

**Issue by adriens** [adriens/covid19-action-plan-nc#22]
# Fonctionnalité

Afin de permettre un meilleur partage lorsque l'url est chargée sur les medias sociaux (preview, premiers élemnts de synthsèe, etc...)
Via les balises meta

https://ogp.me/

# NB

Ceci est une idée de [Guénolé Bouvet](https://www.linkedin.com/in/gu%C3%A9nol%C3%A9-bouvet-3859b990/)

**Comment by adriens** [comment]
Tu vas t'en sortir ? Pas trop chaud à mettre en oeuvre ?


![image](https://user-images.githubusercontent.com/5235127/77714248-9e01a000-702c-11ea-9812-398fb6041a11.png)

**Comment by sschorgen** [comment]
je regarde cela ce week-end :)

**Comment by adriens** [comment]
Pas forcément évident mais super sexy

**Comment by sschorgen** [comment]
C'est fait :)

![image](https://user-images.githubusercontent.com/11071408/77814457-63b80180-7105-11ea-8e68-f213479fd1b0.png)

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/77815519-e47bfb00-710f-11ea-94eb-e5c7b90d7af7.png)

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/77815529-f8bff800-710f-11ea-9413-c282e2480655.png)

**Comment by adriens** [comment]
👏  @sschorgen trop stylé !!!! 🎆

**Comment by adriens** [comment]
Je valide 💯 ❗️ 🥇

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/77816220-180d5400-7115-11ea-816e-78d92589effd.png)

**Comment by adriens** [comment]
Validé par demandeur, je ferme.
