### ISSUE TITLE
Compter le nombre de jours depuis la crise

### ISSUE THREAD

**Issue by adriens** [adriens/covid19-action-plan-nc#25]
Depuis le Day0, du premier cas, compter le nombre de jours écoulés et le remonter dans une score card.
Eventuellement mettre un code couleur, par exemple au dela de deux semaines car on sait que passés les 10j c'est là que ça devient chaud.

**Comment by adriens** [comment]
en rapport avec #32 : ces deux scorecards pourraient être collées l'une à l'autre

**Comment by sschorgen** [comment]
on part de quel jour ? 
1er cas ou quand ils ont commencé à faire des tests (on a pas trop cette info)

**Comment by adriens** [comment]
Je pensais plus à:

> Nb de jours depuis le premer cas testé positif

**Comment by sschorgen** [comment]
Done

**Comment by sschorgen** [comment]
![image](https://user-images.githubusercontent.com/11071408/77718479-27b66b00-7037-11ea-8267-4988e6bf9a06.png)

**Comment by adriens** [comment]
Clean

![image](https://user-images.githubusercontent.com/5235127/77718544-4f0d3800-7037-11ea-95ac-d8e001c5bc61.png)
