### ISSUE TITLE
Il manque certaines données du 23/03/2020

### ISSUE THREAD

**Issue by adriens** [adriens/covid19-action-plan-nc#26]
- on a rien sur les depistages 17/03, 18/03 et 19/03
- pour le 19/03 de mémoire on a mis 18

**Comment by adriens** [comment]
Je vois avec les Nouvelles Calédoniennes

**Comment by adriens** [comment]
Je tente de voir avec [Jean-Frédéric Gallo](https://www.linkedin.com/in/jean-fr%C3%A9d%C3%A9ric-gallo-28a43b87/) y'a de bonnes chances qu'ils aient cela dans les archives pour le coup.

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/77610333-82d45900-6f76-11ea-9b23-b9b896561516.png)

**Comment by sschorgen** [comment]
Pour les autres jours, ca a été communiqué sur la page FB gouv ou covid19.nc

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/77610400-b8794200-6f76-11ea-8a0b-79c71d02cf8d.png)

**Comment by adriens** [comment]
Ne sera pas fixé
