### ISSUE TITLE
Code couleur légende pas adapté au chart

### ISSUE THREAD

**Issue by adriens** [adriens/covid19-action-plan-nc#27]
![image](https://user-images.githubusercontent.com/5235127/77613059-e01fd880-6f7d-11ea-8d7d-4c43c336af0b.png)

**Comment by sschorgen** [comment]
![image](https://user-images.githubusercontent.com/11071408/77613659-5cff8200-6f7f-11ea-800f-8b0f281b47d2.png)

Done !

**Comment by adriens** [comment]
Je confirme
![image](https://user-images.githubusercontent.com/5235127/77615210-dd73b200-6f82-11ea-95ea-a2f8db639c93.png)
