### ISSUE TITLE
Amélioration lisibilité des annonces

### ISSUE THREAD

**Issue by adriens** [adriens/covid19-action-plan-nc#28]
Actuellement le texte de chaque annonce n'a pas d'items, tout en monobloc, ce n'est psa optimal pour la lisiilité.:

![image](https://user-images.githubusercontent.com/5235127/77613890-fdee3d00-6f7f-11ea-9bc4-29f9f0222726.png)

# Proposition

Basculer sur quelque'chose dans le genre:

- 0 nouveau cas dépisté à 15h.
- Nous sommes toujours à 14 cas confirmés total
- 59 tests ont été réalisés jusqu'à 15h00 ce jour
- Les 14 personnes actuellement placées au Médipôle sont dans une état stable
- Des avions se sont posés à Tontouta uniquement pour le fret (pas de passagers)
- Le plan de rapatriement des calédoniens à l'étranger est en cours de définition. Les conditions seront strictes. Uniquement les résidents seront rapatrier. 5 mesures ont été annoncées et seront publiées. Chaque calédonien rentrant sur le territoire sera soit en confinement strict chez lui, soit dans un hôtel ou au CISE et si nécessaire au Médipôle

## NB

_Un décalage de 26 dépistages est présent entre l'annonce du gouvernement de ce jour et nos données. Nous avons en effet commencé la collecte de données à partir du 19/03/2020 et n'avons pas les chiffres du 17/03 et 18/03. Nous essayons de trouver ces informations et corrigeront les chiffres une fois les éléments trouvés. Pour être juste vis à vis du chiffre total annoncé par le gouvernement, nous avons ajouté ses cas sur les journée du 17/03 et 18/03._

**Comment by sschorgen** [comment]
Yes ce week-end as well :)

**Comment by adriens** [comment]
Tu touves donc que c une bonne idée 😸

**Comment by sschorgen** [comment]
Done aussi

**Comment by sschorgen** [comment]
![image](https://user-images.githubusercontent.com/11071408/77718499-33a22d00-7037-11ea-80f4-913a99e76622.png)

**Comment by adriens** [comment]
Je vois ça, en effet, c très propre

![image](https://user-images.githubusercontent.com/5235127/77718493-31d86980-7037-11ea-99f4-c8b32da86cd3.png)

**Comment by adriens** [comment]
C propre 👍
