### ISSUE TITLE
Date des annonces plus "sexy"

### ISSUE THREAD

**Issue by adriens** [adriens/covid19-action-plan-nc#29]
Actuellement, la date se présente ainsi:

![image](https://user-images.githubusercontent.com/5235127/77614189-b2885e80-6f80-11ea-8dd8-aff9ccf78e5f.png)

L'idée serait de partir sur quelqe'chose de plus graphique et qui encombre moins la page genre comme ceci:

![image](https://user-images.githubusercontent.com/5235127/77614245-ca5fe280-6f80-11ea-8c60-5e1f786116f5.png)

Par-contre, faut mettre l'heure...

**Comment by sschorgen** [comment]
je regarde si je trouve des choses plus sexy (je ne te garantie pas cette feature :p)

**Comment by adriens** [comment]
Prio basse et sinon, on la dégagera

**Comment by adriens** [comment]
Abandonné
