### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by adriens** [adriens/covid19-action-plan-nc#31]
"Données mise à jour le 26/03/20 15h00"

devrait être (checker le s)

"Données mises à jour le 26/03/20 15h00"

**Comment by sschorgen** [comment]
Corrigé :)

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/77630030-8976c680-6f9e-11ea-8923-54433d24cfb4.png)
