### ISSUE TITLE
Nombre de jours de confinements

### ISSUE THREAD

**Issue by adriens** [adriens/covid19-action-plan-nc#32]
Dans une Score Card, afficher le nombre de jounrs de confinements.

**Sachant que le confinement a été lancé le Lundi 23/03/2020 à minuit**

**Comment by sschorgen** [comment]
je l'intègre ce week-end également

**Comment by sschorgen** [comment]
Le week-end c'était dans trop longtemps :)
Done

**Comment by sschorgen** [comment]
![image](https://user-images.githubusercontent.com/11071408/77718443-13726e00-7037-11ea-9ae7-e6d49eb4f8d6.png)

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/77718440-12414100-7037-11ea-8a3d-eab63f37a2b7.png)
