### ISSUE TITLE
Belle 404 ou redirection sur le Tdb

### ISSUE THREAD

**Issue by adriens** [adriens/covid19-action-plan-nc#33]
Suite à une coquille, je me suis tapé une 404, du coup, idée : une gestion propre des 404:

![image](https://user-images.githubusercontent.com/5235127/77636576-6fda7c80-6fa8-11ea-9931-686318e9feba.png)

**Comment by sschorgen** [comment]
jouable pour moi je fais cela ce week-end :)

**Comment by sschorgen** [comment]
et c'est fait :)

![image](https://user-images.githubusercontent.com/11071408/77719763-36525180-703a-11ea-9c4d-81eb0a36003a.png)

**Comment by adriens** [comment]
Testé et validé 👏
