### ISSUE TITLE
Légende manquante sur les dépistages par jour

### ISSUE THREAD

**Issue by adriens** [adriens/covid19-action-plan-nc#34]
![image](https://user-images.githubusercontent.com/5235127/77751860-8d781680-707a-11ea-836f-b8983ee8789f.png)

**Comment by sschorgen** [comment]
![image](https://user-images.githubusercontent.com/11071408/77814140-7250e980-7102-11ea-8b2e-2c35f83c4c2c.png)

C'est corrigé
