### ISSUE TITLE
Ajouter le nombre de  nombre de tests réalisés quotidiennement

### ISSUE THREAD

**Issue by adriens** [adriens/covid19-action-plan-nc#37]
Remonté ce jour via le portai Open Data gouv fr par [Jean-Baptiste Leroux](https://www.data.gouv.fr/fr/users/jean-baptiste-leroux/) 👍 

![image](https://user-images.githubusercontent.com/5235127/77836588-987e9400-71ab-11ea-9f55-f32df455ffa8.png)

Je tenterai d'incorporer les données du passé également

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/77836633-f7440d80-71ab-11ea-97f7-8ac7bbee0a38.png)

**Comment by adriens** [comment]
@sschorgen tu as gardé l'historique du nombre de tests réalisés, jour par jour ? 🙏

**Comment by sschorgen** [comment]
J'ai les valeurs que depuis le 19/03 :

date,value
"19/03/20",18
"20/03/20",28
"21/03/20",40
"22/03/20",62
"23/03/20",71
"24/03/20",106
"25/03/2020",111
"26/03/2020",121
"27/03/2020",187
"28/03/2020",98

**Comment by adriens** [comment]
c parfait @sschorgen  🚀

**Comment by adriens** [comment]
Intégration en cours...

**Comment by adriens** [comment]
Je ne changerai pas les fichiers du passé car ils sont signés.
J'ai complété 
![image](https://user-images.githubusercontent.com/5235127/77837347-e4353b80-71b3-11ea-9cbd-c627fd80ae7f.png)

**Comment by adriens** [comment]
Ces nouvelles données apparaîtront dès  la prochaine publication à priori ce soir ✔️

**Comment by adriens** [comment]
Je fmerai le ticket une fois la publication effectuée ☑️

**Comment by adriens** [comment]
AJouté à la mise à jour de ce soir cf https://static.data.gouv.fr/resources/covid19-nouvelle-caledonie/20200329-104557/covid19-nc-2020-03-29-19h30.csv
