### ISSUE TITLE
Rendre le tableau de bord responsive

### ISSUE THREAD

**Issue by adriens** [adriens/covid19-action-plan-nc#5]
Affichage optimal sur

- PC
- mobile

**Comment by adriens** [comment]
Sylver est dessus

**Comment by sschorgen** [comment]
Nouvelle version sur http://covid19nc.schorgen.com s'adapte un peu mieux au mobile en paysage

**Comment by adriens** [comment]
✔️

**Comment by sschorgen** [comment]
Développement d'une version compatible mobile / tablette / pc done :)

**Comment by adriens** [comment]
Testé tel,tablette et pc ✔️
