### ISSUE TITLE
Sur le tableau de bord PowerBI donner le code embeddable html

### ISSUE THREAD

**Issue by adriens** [adriens/covid19-action-plan-nc#6]

**Comment by adriens** [comment]
Ajouter un bouton qui permet de copier coller le code html

**Comment by sschorgen** [comment]
Sera fait pour la version de ce soir :)

**Comment by adriens** [comment]
AH, on garde alors ?

**Comment by adriens** [comment]
Trop peu de valeur en regard de la complexité.
Je rejette cette issue afin de garder un débit fluide.
