### ISSUE TITLE
Bug sur le maj automatique du TDB

### ISSUE THREAD

**Issue by adriens** [adriens/covid19-action-plan-nc#8]
![image](https://user-images.githubusercontent.com/5235127/77247039-59b77e00-6c81-11ea-831a-dbb094237fd5.png)

**Comment by adriens** [comment]
Inestigations en cours par @sschorgen

**Comment by adriens** [comment]
> pas touché le param pour les score card
> 
> du coup pas le bon lien

**Comment by adriens** [comment]
Fix en cours...

**Comment by adriens** [comment]
vidage de cache forcé en cours...

**Comment by adriens** [comment]
Fixé ✔️ 
![image](https://user-images.githubusercontent.com/5235127/77247124-190c3480-6c82-11ea-912a-284de2eec48f.png)

**Comment by adriens** [comment]
Merci @sschorgen pour le fix 🚀

**Comment by sschorgen** [comment]
Ok corrigé.
Le bug venait du lien de la source de données qui n'était pas corrigé dans une source de données côté PowerBI. C'est chose faite !

**Comment by sschorgen** [comment]
![image](https://user-images.githubusercontent.com/11071408/77247135-4953d300-6c82-11ea-971e-50679c986643.png)
