### ISSUE TITLE
Ajouter la date de dernière mise à jour au tdb

### ISSUE THREAD

**Issue by adriens** [adriens/covid19-action-plan-nc#9]
Actuellement on ne sait pas de quand date les chiffres de manière évidente, i lserait bon de mettre la date en évidence.

**NB: bien se baser sur la dernière date du jeu de données**

**Comment by sschorgen** [comment]
Jour et heure ajouté dans le bloc de texte en bas à droite.

![image](https://user-images.githubusercontent.com/11071408/77247332-29251380-6c84-11ea-961b-dc4d6acd0ee5.png)

**Comment by adriens** [comment]
Poussé à `Done` ✔️
